syntax = "proto3";

package uniflow;

enum FileOperation {
    WRITE = 0;
    DELETE = 1;
}

message FilePacket {
    string file_id = 1;
    string file_name = 2;

    uint64 file_size = 3;
    string file_hash = 4;

    uint32 packet_index = 5;
    uint32 total_packets = 6;

    uint32 target_receiver = 7;

    bytes data = 8;

    uint32 block_index = 9;
    uint32 total_blocks = 10;
    uint64 block_size = 11;

    string packet_hash = 12;
    uint32 symbol_size = 13;
    uint64 block_offset = 14;

    FileOperation operation = 15;
}
